# Generated by Django 4.1.1 on 2022-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeehouse',
            name='coffee_image',
            field=models.ImageField(blank=True, null=True, upload_to='coffees_images/'),
        ),
    ]
