# Generated by Django 4.0.4 on 2022-10-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouse', '0002_coffeehouse_coffee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeehouse',
            old_name='bike_frendly',
            new_name='bike_friendly',
        ),
    ]
