# Generated by Django 4.1.1 on 2022-10-05 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouse', '0003_rename_bike_frendly_coffeehouse_bike_friendly'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='house',
        ),
        migrations.AddField(
            model_name='favorite',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffeehouse.coffeehouse'),
        ),
    ]
