# Generated by Django 4.1.1 on 2022-10-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouse', '0003_rename_bike_frendly_coffeehouse_bike_friendly'),
        ('favorites', '0002_remove_favorite_house_favorite_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='house',
        ),
        migrations.AddField(
            model_name='favorite',
            name='house',
            field=models.ManyToManyField(to='coffeehouse.coffeehouse'),
        ),
    ]
